# Generated by Django 5.1.7 on 2025-03-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=5)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='trainee_pictures/')),
                ('courses', models.ManyToManyField(related_name='trainees', to='course.course')),
            ],
        ),
    ]
